sonar.projectKey=guigozt_entrega_continua
sonar.organization=guigozt

sonar.projectName=entrega_continua

sonar.sources=Calculator
sonar.exclusions=Calculator/test_*.py

sonar.tests=Calculator
sonar.test.inclusions=Calculator/test_*.py

sonar.python.version=3.12
sonar.python.coverage.reportPaths=Calculator/coverage.xml

sonar.sourceEncoding=UTF-8