name: Calculator

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - 'Calculator/**'

  pull_request:
    branches: [main]
    paths:
      - 'Calculator/**'

jobs:
  somar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pytest
        run: pip install pytest

      - name: Testar soma
        working-directory: Calculator
        run: pytest test_soma.py -k test_somar

  subtrair:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pytest
        run: pip install pytest

      - name: Testar subtração
        working-directory: Calculator
        run: pytest test_subtrai.py -k test_subtrair

  multiplicar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pytest
        run: pip install pytest

      - name: Testar multiplicação
        working-directory: Calculator
        run: pytest test_multiplica.py -k test_multiplicar

  dividir:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pytest
        run: pip install pytest

      - name: Testar divisão
        working-directory: Calculator
        run: pytest test_dividi.py