name: CI Node.js

on:
  push:
    branches: [main]
    paths:
      - 'Calculator_2/**'

  pull_request:
    branches: [main]
    paths:
      - 'Calculator_2/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Calculator_2/package-lock.json

      - name: Instalar dependências
        working-directory: Calculator_2
        run: npm ci

      - name: Linter
        working-directory: Calculator_2
        run: npm run lint

      - name: Testes unitários e Cobertura
        working-directory: Calculator_2
        run: npm run test:coverage

      - name: Análise de segurança
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown