name: Second Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name : Compilator Java
        working-directory: Calculator_2
        run: javac Main.java

      - name: Executar Java
        working-directory: Calculator_2
        run: java Main

